export const ICON = {
  user: 'pi-user',
  cart: 'pi-shopping-cart',
  mobileMenu: 'pi-bars',
  orders: 'pi-box',
  addToCart: 'pi-cart-plus',
  userProfile: 'pi-cog',
  logout: 'pi-sign-out',
  loading: 'pi-spin pi-spinner',
  trash: 'pi-trash',
  plus: 'pi-plus',
  minus: 'pi-minus',
  reset: 'pi-undo',
  warning: 'pi-exclamation-triangle',
}
